version: "3.3"

services:
  bot:
    build: .
    env_file: .env
    depends_on:
      - db
    networks:
      - internal
    volumes:
      - ./logs:/code/logs
  db:
    image: mysql:latest
    command: --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_ROOT_PASSWORD: supersecretpassword
    networks:
      - internal
  adminer:
    image: adminer
    depends_on:
      - db
    ports:
      - 8080:8080
    networks:
      - internal

networks:
  internal:
    driver: bridge
